version: '2'
services:
  database:
    scale: 1
  haproxy:
    lb_config:
      certs: []
      port_rules:
      - hostname: ''
        path: ''
        protocol: http
        service: SonarQube/sonar
        source_port: 9000
        target_port: 9000
    load_balancer_config:
      haproxy_config: {}
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      interval: 2000
  sonar:
    scale: 1
